### PR TITLE
Aquavanjaram942_80cu BBS and HHS NN TN NT GEMM tuning

### PR DESCRIPTION
**Pull request by aferoz21**
1) BF16 NN, TN ,NT BF16 grid points improvement. ~14% improvement done.

### CODE REVIEW

**Comment by aferoz21** [comment]
hipBLAS-test results

[----------] 1 test from ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest.amaxFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest.amaxFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest (0 ms total)

[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (807119 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test

**Review by KKyang — DISMISSED** [review]

**Comment by aferoz21** [comment]
1) HHS equivalent kernels for grid points validated and merged.

**Comment by aferoz21** [comment]
HHS equivalent of BBS kernels converted , validated and merged.

**Review by nakajee — APPROVED** [review]
Looks good.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
