### PR TITLE
PrintSolutionRejectionReason = True doesn't work at 4_LibraryClient stage

### PR DESCRIPTION
**Pull request by Jay0521**

### CODE REVIEW

**Review by jichangjichang — COMMENTED** [review]
stage4 should always be able to generate the winner solutions.
Which case you encountered still fails to be generated in stage4?

**Comment by Jay0521** [comment]
> stage4 should always be able to generate the winner solutions. Which case you encountered still fails to be generated in stage4?

After this PR (https://github.com/ROCm/hipBLASLt/pull/1228), some sparse kernels cannot be generated. I want to find out the reason for kernel failure from stage 4, but currently, I can only set PrintSolutionRejectionReason = True in common.py. Therefore, I modified this part so that PrintSolutionRejectionReason can be set directly from the YAML file and executed correctly. Is this modification feasible?

**Comment by jichangjichang** [comment]
> > stage4 should always be able to generate the winner solutions. Which case you encountered still fails to be generated in stage4?
> 
> After this PR (#1228), some sparse kernels cannot be generated. I want to find out the reason for kernel failure from stage 4, but currently, I can only set PrintSolutionRejectionReason = True in common.py. Therefore, I modified this part so that PrintSolutionRejectionReason can be set directly from the YAML file and executed correctly. Is this modification feasible?

If a kernel is generated failed in stage1, it shouldn't be target in stage4.

**Comment by Jay0521** [comment]
> > > stage4 should always be able to generate the winner solutions. Which case you encountered still fails to be generated in stage4?
> > 
> > 
> > After this PR (#1228), some sparse kernels cannot be generated. I want to find out the reason for kernel failure from stage 4, but currently, I can only set PrintSolutionRejectionReason = True in common.py. Therefore, I modified this part so that PrintSolutionRejectionReason can be set directly from the YAML file and executed correctly. Is this modification feasible?
> 
> If a kernel is generated failed in stage1, it shouldn't be target in stage4.

Understand. Thanks.

**Pull request closed without merging**
