### PR TITLE
Enable WGM=-1 in ContractionSolution.

### PR DESCRIPTION
**Pull request by hcman2**
In previous PR, I forget to modify ContractionSolution.
Fixed in this patch.

### CODE REVIEW

**Comment by hcman2** [comment]
@nakajee Please help to review this PR. If there are still any parts we need to modify please remind me. Thanks.

**Review by nakajee — COMMENTED** [review]
I double-checked negative WGM enablement commit.
Looks like this is the only change we need in this file.
The change looks ok.
I enabled gfx94x CI test.
wgm.yaml seems to be skipped for other architectures.

**Review by nakajee — APPROVED** [review]
CI test is disabled for now...
The change looks good.

**Comment by hcman2** [comment]
===== 62 passed, 18 skipped, 1 xfailed, 24 warnings in 13072.82s (3:37:52) =====
tensilelite test passed

**Comment by hcman2** [comment]
[----------] Global test environment tear-down
[==========] 37294 tests from 13 test suites ran. (1756548 ms total)
[  PASSED  ] 37294 tests.

**Review by Jinp800125 — APPROVED** [review]
LGTM

**Pull request merged**
