### PR TITLE
gfx942_80CU HHS/BBS NN GridBased

### PR DESCRIPTION
**Pull request by babakpst**

### CODE REVIEW

**Comment by babakpst** [comment]
- The same library is used for BBS and HHS. 
- Total number of sizes: 6855

**Comment by nakajee** [comment]
Regarding this,
- The same library is used for BBS and HHS.

It is not a big deal, but the number of kernel is not exactly same between HHS and BBS.

**Comment by babakpst** [comment]
Correct. And thanks for the comment. After benchmarking, there were a few sizes different in HHS and BBS with perf drop compared to gfx942. After adjusting for the perf drops, the number of kernels changed in HHS and BBS.

**Review by nakajee — APPROVED** [review]
Looks good

**Review by KKyang — APPROVED** [review]

**Pull request merged**
