### PR TITLE
Update dependency list with the actual package name

### PR DESCRIPTION
**Pull request by raramakr**
hipblas-common-devel/dev is the actual package name and it provides hipblas-common. Use the actual package name in dependency.

### CODE REVIEW

**Review by nunnikri — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
lgtm, please also file hotfix PR into release-staging/rocm-rel-6.3 branch

**Comment by raramakr** [comment]
> lgtm, please also file hotfix PR into release-staging/rocm-rel-6.3 branch

Thank you @jichangjichang  
Will raise a PR to release-staging/rocm-rel-6.3 as well

**Comment by awhittle3** [comment]
Friendly reminder to close this PR in favour of #1170 and #1176

**Comment by raramakr** [comment]
Handled in https://github.com/ROCm/hipBLASLt/pull/1170

**Pull request closed without merging**
