### PR TITLE
added kernels for BBS/HHS TN/NT/NN to equality for aquavanjaram942

### PR DESCRIPTION
**Pull request by smalekta**
added kernels for BBS/HHS TN/NT/NN to equality for aquavanjaram942

### CODE REVIEW

**Comment by smalekta** [comment]
[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (2444550 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

**Comment by nakajee** [comment]
Please provide perf comparison for HHS and BBS separately and make sure no perf regression for both.

**Comment by smalekta** [comment]
Removed some of the kernels that did not show significant uplift (and could cause slight regressions due to variance in run to run perf). Test are passing on latest commit 

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (2557523 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

**Review by babakpst — APPROVED** [review]

**Review by KKyang — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
please use squash merge

**Pull request merged**
