### PR TITLE
Tune aquavanjaram942 HHS NN TN NT batched sizes

### PR DESCRIPTION
**Pull request by aferoz21**
1) Below sizes tuned, overall 11% improvement on the weighted average for the tuned sizes.
2) GEMM Sizes updated in equality.

HHS NT
[178, 64, 6144, 178]
[64, 178, 6144, 178]
  
HHS NN
[64, 178, 6144, 178]
[178, 178, 6144, 64]

HHS TN
[64, 178, 6144, 178]

### CODE REVIEW

**Comment by aferoz21** [comment]
will update the hipBLAS-test results. it is currently running.

**Comment by aferoz21** [comment]
hipBLAS-test result

[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (2129186 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test

**Comment by nakajee** [comment]
Please fix the typo in the title
  HHHS -> HHS

**Comment by nakajee** [comment]
Did you try MT192x64 for 178x64 and MT192x192 (or 192x64) for 178x178?

**Comment by aferoz21** [comment]
> Did you try MT192x64 for 178x64 and MT192x192 (or 192x64) for 178x178?
Thank you, 192x64 worked and improved 10% in total weight time from previous run.

**Review by KKyang — APPROVED** [review]

**Comment by aferoz21** [comment]
Latest hipBLAS-test run results

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (3529559 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test

**Review by nakajee — APPROVED** [review]
Thanks for your update.
Looks good.

**Pull request merged**
