### PR TITLE
gfx942 80cu BBS/HHS TN GridBased + Equality tuning and Shrinking

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by nakajee** [comment]
- same tuning config for both BBS and HHS
- 209 existing sizes (each BBS, HHS GridBased)
- 59 new sizes  (each BBS, HHS GridBased)
- 1 existing size (each BBS, HHS Equality)
- reduced the amount of sizes in M,N,K directions (around by half)

**Comment by nakajee** [comment]
The tuning in this PR requires PR #817 to get correct results.

**Review by aferoz21 — APPROVED** [review]
Looks good.

**Review by aazz44ss — APPROVED** [review]
LGTM

**Review by babakpst — APPROVED** [review]

**Pull request merged**
