### PR TITLE
add aquavanjaram942X_20CU libraries for HHS/BBS/TF32/I8I8I

### PR DESCRIPTION
**Pull request by babakpst**

### CODE REVIEW

**Comment by babakpst** [comment]
hipblaslt-test passed locally on my node:

[----------] Global test environment tear-down
[==========] 35356 tests from 13 test suites ran. (2227434 ms total)
[  PASSED  ] 35356 tests.
hipBLASLt version: 800

**Comment by jichangjichang** [comment]
May I know the hipblaslit library size with/wo this PR?
Command to check library size
sudo du --max-depth=0 --block-size=M build/release/hipblaslt-install/

**Comment by babakpst** [comment]
@jichangjichang shared privately in the chat.

**Comment by jichangjichang** [comment]
@babakpst  Please get approval from NA team first.

**Comment by babakpst** [comment]
I am working on this. Thanks for reminding me.

**Review by nakajee — APPROVED** [review]
Looks good

**Comment by jichangjichang** [comment]
please provide local test result for latest change

**Comment by babakpst** [comment]
Tests after the second commint:

[----------] Global test environment tear-down
[==========] 35356 tests from 13 test suites ran. (2131781 ms total)
[  PASSED  ] 35356 tests.
hipBLASLt version: 800

command line: ./hipblaslt-test

**Review by KKyang — APPROVED** [review]

**Pull request merged**
