### PR TITLE
Add GB/s into hipblaslt-bench output

### PR DESCRIPTION
**Pull request by boringmorning**

### CODE REVIEW

**Comment by boringmorning** [comment]
Command line GB/s output:

螢幕擷取畫面 2024-09-10 120304

**Review by jichangjichang — DISMISSED** [review]
lgtm

**Review by Serge45 — DISMISSED** [review]

**Review by solaslin — CHANGES_REQUESTED** [review]
please update the benchmark csv script as well:

See:
**clients/scripts/performance/bench.py , line 92**
you may need to add 
`line = line.replace('hipblaslt-GB/s', 'GB/s')`

And 
**clients/scripts/performance/hipblaslt-perf, line 39**
Please insert 'GB/s' between the last two 'gflops','us'. 
i.e.` ...'gflops','GB/s','us']` so that the csv file contains this field.

**Comment by solaslin** [comment]
> please update the benchmark csv script as well:
> 
> See: **clients/scripts/performance/bench.py , line 92** you may need to add `line = line.replace('hipblaslt-GB/s', 'GB/s')`
> 
> And **clients/scripts/performance/hipblaslt-perf, line 39** Please insert 'GB/s' between the last two 'gflops','us'. i.e.` ...'gflops','GB/s','us']` so that the csv file contains this field.

after you finish updating the script, please try 
**`./clients/scripts/performance/hipblaslt-perf --suite all`** 
to see if the csv data file looks good without empty value

**Comment by boringmorning** [comment]
> please update the benchmark csv script as well:
> 
> See: **clients/scripts/performance/bench.py , line 92** you may need to add `line = line.replace('hipblaslt-GB/s', 'GB/s')`
> 
> And **clients/scripts/performance/hipblaslt-perf, line 39** Please insert 'GB/s' between the last two 'gflops','us'. i.e.` ...'gflops','GB/s','us']` so that the csv file contains this field.

Done. The .csv output looks fine.
螢幕擷取畫面 2024-09-16 192753

**Review by solaslin — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
lgtm

**Comment by boringmorning** [comment]
Local test:
 1. gfx90a
螢幕擷取畫面 2024-09-19 185707

 2. gfx942
螢幕擷取畫面 2024-09-19 194912

**Pull request merged**
