### PR TITLE
Refine local read scheduling logic.

### PR DESCRIPTION
**Pull request by hcman2**
1. The original logic are different in SIA and scheduling. Make sure that they are the same.
2. Fix scheduling iter by iter logic.

### CODE REVIEW

**Comment by hcman2** [comment]
[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (787145 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1100

**Review by KKyang — APPROVED** [review]

**Comment by hcman2** [comment]
-- generated xml file: /menghung/hcman/hipBLASLt/tensilelite/python_tests.xml --
========== 77 passed, 32 skipped, 1317 warnings in 8746.84s (2:25:46) ==========

**Comment by hcman2** [comment]
image
The previous version didn't consider the cross-iter scheduling.
The FIFO is reset for every iter. 
Refine the FIFO rule for cross-iter optimization.

**Review by aazz44ss — APPROVED** [review]
LGTM

**Pull request merged**
