### PR TITLE
gfx12 - enable I8I8I

### PR DESCRIPTION
**Pull request by cmingch**

### CODE REVIEW

**Review by wenchuanchen — DISMISSED** [review]

**Review by jichangjichang — COMMENTED** [review]
the enablement yaml should apply to Gridbased

**Comment by jichangjichang** [comment]
Any hipblaslt CI tests for navi i8I8I?

**Comment by cmingch** [comment]
> the enablement yaml should apply to Gridbased

done

**Comment by cmingch** [comment]
> Any hipblaslt CI tests for navi i8I8I?
only tox.
just added gtest in this PR for gfx11/12. there's no test case for gfx11 when enabling i8i8i.
about skinny i8, will have another PR since gfx11 yaml don't support it yet.

**Comment by cmingch** [comment]
gfx12 result
image

gfx11 result
image

**Comment by TonyYHsieh** [comment]
.../Tensile/Logic/asm_full/gfx1201/GridBased/gfx1201_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml_bak
what is this???

**Comment by cmingch** [comment]
> .../Tensile/Logic/asm_full/gfx1201/GridBased/gfx1201_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml_bak what is this???

garbage, removed

**Review by hcman2 — APPROVED** [review]
ok

**Review by jichangjichang — APPROVED** [review]
lgtm

**Pull request merged**
