### PR TITLE
Tune aquavanjaram942 80CU compute bound and memory bound HHS NN GEMM sizes

### PR DESCRIPTION
**Pull request by aferoz21**
1) 7.5% improvement from base version for compute bound (HHS, NN)
2) 88.7% improvement for Memory bound (HHS, NN)

HHS 
80cu BaseVsTuned Compute Bound=> 7.5%		
80cu BaseVsTuned Memory bound=> 88.7% 		

BBS
80cu BaseVsTuned Compute Bound=> 8.4%		
80cu BaseVsTuned Memory bound=> 88.7%

### CODE REVIEW

**Comment by nakajee** [comment]
The tuned perf looks good.
What you can try is 
- VectorWidthA, B: add -1
- NonTemporalC, D: add 4
- NN case, MIWaveGroup=[4,1] is better in general. Please try more MT sizes with MIWG=[4,1]. Like followings
MatrixInstruction: [16, 16, 16,  1,  1,   4,   9,  4,   1]  # MT 256x144
MatrixInstruction: [16, 16, 16,  1,  1,   4,  10,  4,   1]  # MT 256x160
MatrixInstruction: [16, 16, 16,  1,  1,   4,  11,  4,   1]  # MT 256x176
MatrixInstruction: [16, 16, 16,  1,  1,   4,  12,  4,   1]  # MT 256x192
MatrixInstruction: [16, 16, 16,  1,  1,   4,  13,  4,   1]  # MT 256x208
MatrixInstruction: [16, 16, 16,  1,  1,   4,  14,  4,   1]  # MT 256x224
MatrixInstruction: [16, 16, 16,  1,  1,   4,  15,  4,   1]  # MT 256x240
MatrixInstruction: [16, 16, 16,  1,  1,   4,  16,  4,   1]  # MT 256x256
MatrixInstruction: [32, 32,  8,  1,  1,  2,   4,  4,   1]  # MT 256x128
MatrixInstruction: [32, 32,  8,  1,  1,  2,   5,  4,   1]  # MT 256x160
MatrixInstruction: [32, 32,  8,  1,  1,  2,   6,  4,   1]  # MT 256x192
MatrixInstruction: [32, 32,  8,  1,  1,  2,   7,  4,   1]  # MT 256x224
MatrixInstruction: [32, 32,  8,  1,  1,  2,   8,  4,   1]  # MT 256x256
- you do not need to try MIB>1. It will not perform well in general (good for very small K only)
- No need to use PrefetchLocalRead=3,5,9. They are basically for Tensile and does not perform well with tensilelite (you can see PLR=1 wins at all sizes). If you would like to try PLR>1, you can try 2

**Review by KKyang — APPROVED** [review]

**Comment by aferoz21** [comment]
> The tuned perf looks good. What you can try is
> 
> * VectorWidthA, B: add -1
> * NonTemporalC, D: add 4
> * NN case, MIWaveGroup=[4,1] is better in general. Please try more MT sizes with MIWG=[4,1]. Like followings
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,   9,  4,   1]  # MT 256x144
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  10,  4,   1]  # MT 256x160
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  11,  4,   1]  # MT 256x176
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  12,  4,   1]  # MT 256x192
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  13,  4,   1]  # MT 256x208
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  14,  4,   1]  # MT 256x224
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  15,  4,   1]  # MT 256x240
>   MatrixInstruction: [16, 16, 16,  1,  1,   4,  16,  4,   1]  # MT 256x256
>   MatrixInstruction: [32, 32,  8,  1,  1,  2,   4,  4,   1]  # MT 256x128
>   MatrixInstruction: [32, 32,  8,  1,  1,  2,   5,  4,   1]  # MT 256x160
>   MatrixInstruction: [32, 32,  8,  1,  1,  2,   6,  4,   1]  # MT 256x192
>   MatrixInstruction: [32, 32,  8,  1,  1,  2,   7,  4,   1]  # MT 256x224
>   MatrixInstruction: [32, 32,  8,  1,  1,  2,   8,  4,   1]  # MT 256x256
> * you do not need to try MIB>1. It will not perform well in general (good for very small K only)
> * No need to use PrefetchLocalRead=3,5,9. They are basically for Tensile and does not perform well with tensilelite (you can see PLR=1 wins at all sizes). If you would like to try PLR>1, you can try 2

I tried all these config parameters got a small improvement of 0.5% to 0.7% as an average.

**Comment by nakajee** [comment]
Looks like some issue with merging develop changes.
Please resolve the issue.
Perf improvement looks good.

**Comment by babakpst** [comment]
@aferoz21 did you already merged your final library?

**Comment by aferoz21** [comment]
> @aferoz21 did you already merged your final library?
Yes final library has been merged.

**Review by nakajee — APPROVED** [review]
Looks good.

**Pull request merged**
