### PR TITLE
readme and changelog edits

### PR DESCRIPTION
**Pull request by LisaDelaney**

### CODE REVIEW

**Comment by imcarsonliao** [comment]
@jichangjichang  please check lisa's modificaiton.

**Comment by jichangjichang** [comment]
@LisaDelaney  Should we apply this to rocm 6.0 branch as well?

**Review by jichangjichang — APPROVED** [review]
lgtm

**Comment by LisaDelaney** [comment]
> @LisaDelaney Should we apply this to rocm 6.0 branch as well?

It would be nice if we could...but not a tragedy if we can't.  :)

**Review by KKyang — APPROVED** [review]

**Comment by jichangjichang** [comment]
@LisaDelaney  Review process is done. Please merge if you don't have other modification.

**Pull request merged**
