### PR TITLE
gfx942 BBS/HHS TN GridBased tuning

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by nakajee** [comment]
- gfx942 BBS TN grid based tuning (774 size tuned (240 size updated, 534 size added))
- converted BBS TN GridBased logic to HHS TN GridBased (ported all changes in BBS TN to HHS TN)
- Some sizes are ported to BBS/HHS Equality to use new tuned kernels for these sizes defined in Equality logic
    - 16 sizes updated in BBS TN Equality
    - 2 sizes updated in HHS TN Equality

**Comment by hcman2** [comment]
We have updated aquavanjaram_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs.yaml several times recently. Did you check the performance difference with the newest yaml on develop branch? The performance on the logic yaml differed with different machine and gpu device. You may double check with Henry Ho.

**Review by babakpst — CHANGES_REQUESTED** [review]
Let's merge #858 first, then, we will get back to this.

**Comment by nakajee** [comment]
I will launch a new PR.
Not easy to resolve the conflict.
I realized #858 updated gfx942_80cu folder (which is different from this).

**Pull request closed without merging**
