### PR TITLE
[Tensilelite] Fixe the conflict GSUM kernel name for I8/H/S and H/H/S

### PR DESCRIPTION
**Pull request by vin-huang**

### CODE REVIEW

**Comment by KKyang** [comment]
Can you give an example why conflict happens?

**Review by KKyang — COMMENTED** [review]
Can you give an example why conflict happens? I thought the first kernel name is I8HS and the second one is HHS. This looks like a workaround method to me.

**Comment by vin-huang** [comment]
for I8/H/S and H/H/S,  they will generate the same kernel like "Cijk_H_BiasS_AS_PostGSU2_VW"
but for I8/H/S its input data is int type, but for H/H/S its input data is float, then caused the conflict.

for example
the data type of "temp" in I8/H/S is **int** , but for H/H/S which is **float**
```
extern "C"
__global__ void extern "C"
__global__ void Cijk_H_BiasS_AS_PostGSU2_VW1(
  argument_Cijk_H_BiasS_AS_PostGSU2_VW1 arg)
{
...
  int temp[NUM_GSU];
  buffer_load<int, sizeof(float), CacheOperation::Kind::Always>(temp[0], arg.W, idxW * sizeof(float), 0);
  idxW  += strideW;
  buffer_load<int, sizeof(float), CacheOperation::Kind::Always>(temp[1], arg.W, idxW * sizeof(float), 0);
  idxW  += strideW;
...
```

**Comment by KKyang** [comment]
> for I8/H/S and H/H/S, they will generate the same kernel like "Cijk_H_BiasS_AS_PostGSU2_VW" but for I8/H/S its input data is int type, but for H/H/S its input data is float, then caused the conflict. so for I8/H/S I add load data type into its kernel name "Cijk_H_**I**_BiasS_AS_PostGSU2_VW"
> 
> for example the data type of "temp" in I8/H/S is **int** , but for H/H/S which is **float**
> 
> ```
> extern "C"
> __global__ void extern "C"
> __global__ void Cijk_H_BiasS_AS_PostGSU2_VW1(
>   argument_Cijk_H_BiasS_AS_PostGSU2_VW1 arg)
> {
> ...
>   int temp[NUM_GSU];
>   buffer_load<int, sizeof(float), CacheOperation::Kind::Always>(temp[0], arg.W, idxW * sizeof(float), 0);
>   idxW  += strideW;
>   buffer_load<int, sizeof(float), CacheOperation::Kind::Always>(temp[1], arg.W, idxW * sizeof(float), 0);
>   idxW  += strideW;
> ...
> ```

I thought I8HS output to workspace is still float? If not should we considering redesign the naming instead?

**Comment by vin-huang** [comment]
modify the KERNEL name  by this format Cijk_{$inputdata}{$destdata}_BiasS_AS_PostGSU2_VW
I8HS: Cijk_IH_BiasS_AS_PostGSU2_VW
HHS: Cijk_SH_BiasS_AS_PostGSU2_VW

**Review by KKyang — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
LGTM

**Pull request merged**
