### PR TITLE
fix correctness issue when TT A or B larger than 1 with half type

### PR DESCRIPTION
**Pull request by TonyYHsieh**
fix correctness issue when TT A or B larger than 1 with half type

### CODE REVIEW

**Comment by TonyYHsieh** [comment]
hipblaslt-test pass on gfx942 and gfx1201

**Review by cmingch — DISMISSED** [review]

**Review by KKyang — COMMENTED** [review]
Why so many space lines?

**Review by jichangjichang — APPROVED** [review]
lgtm

**Review by cmingch — APPROVED** [review]
lgtm

**Comment by TonyYHsieh** [comment]
> Why so many space lines?

it makes code much easier to read.

**Comment by TonyYHsieh** [comment]
hipblaslt-test pass on gfx942

**Pull request merged**
