### PR TITLE
gfx942 HHS NN/TN Equality tuning

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by nakajee** [comment]
HHS NN: 4 new sizes
HHS TN: 4 new sizes

**Comment by nakajee** [comment]
Resolved the conflict.

**Review by babakpst — APPROVED** [review]

**Comment by StaceyLai** [comment]
If your commit involves changes to a YAML file, please take note.

Due to PR-1117 (https://github.com/ROCm/hipBLASLt/pull/1117) adding `ActivationType: hipblaslt_all`, all YAML files now need to include the `ActivationType` field (for hipblaslt logic YAML, use `ActivationType: hipblaslt_all` (not `all`); for tensile test YAML, you can use either `all` or `hipblaslt_all`). 

Correspondingly, in the Logic YAML filename, the `_A` that originally represented `ActivationType: all` should also be changed to `_HA`. These changes have been implemented in PR-1117.

**Comment by nakajee** [comment]
> If your commit involves changes to a YAML file, please take note.
> 
> Due to PR-1117 (#1117) adding `ActivationType: hipblaslt_all`, all YAML files now need to include the `ActivationType` field (for hipblaslt logic YAML, use `ActivationType: hipblaslt_all` (not `all`); for tensile test YAML, you can use either `all` or `hipblaslt_all`).
> 
> Correspondingly, in the Logic YAML filename, the `_A` that originally represented `ActivationType: all` should also be changed to `_HA`. These changes have been implemented in PR-1117.

I checked 1117. This is Equality logic update only and it does not have Activation enabled.
No change needed.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
