### PR TITLE
Update setuptools inside virtualenv

### PR DESCRIPTION
**Pull request by yoichiyoshida**
fix build issues on some systems with newer setuptools

### CODE REVIEW

**Review by babakpst — APPROVED** [review]
We need this change to avoid setuptool version upgrade.

**Comment by nakajee** [comment]
I wanted to confirm if this works with gfx942 CI node, but CI test issue is not resolved yet....
I encountered an issue with this change on my gfx942 node (it happens on my node only... Not sure why).
In my case, I need to specify setuptools version to avoid getting an error with newer verision (72).
   -q -U "setuptools<71.0"

**Comment by KKyang** [comment]
@nakajee  Can you build now? Or is the error still existing?

**Comment by nakajee** [comment]
> @nakajee Can you build now? Or is the error still existing?

The same error I saw before seems not happening with the latest mainline docker.
I think this is OK as long as the build pass with current CI environment.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
