### PR TITLE
gfx942 80cu F8F8S TN GridBased + Equality logic

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by nakajee** [comment]
hipblaslt-test (no option) passed on gfx942 80 cu node.

[----------] Global test environment tear-down
[==========] 35886 tests from 13 test suites ran. (1729309 ms total)
[  PASSED  ] 35886 tests.
hipBLASLt version: 1000

command line: ./build/release/clients/staging/hipblaslt-test

**Comment by nakajee** [comment]
Lib size change observation.
Command: sudo du --max-depth=0 --block-size=M build/release/hipblaslt-install/
Before: 7804M   build/release/hipblaslt-install/
After: 7932M   build/release/hipblaslt-install/

Commit id (before): fedb492f6e709aa3d57a6dcbbe2cca994fffe587
(gfx942 only (-a gfx942))

**Comment by jichangjichang** [comment]
Please get approval from your local team first

**Comment by nakajee** [comment]
Some CI tests failed but seems like unrelated to my change.
I ran hipblaslt test on gfx942 (not 80cu version) with all arch build.
All passed.

[----------] Global test environment tear-down
[==========] 35886 tests from 13 test suites ran. (1822863 ms total)
[  PASSED  ] 35886 tests.
hipBLASLt version: 1000

command line: ./build/release/clients/staging/hipblaslt-test

**Review by babakpst — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
lgtm

**Pull request merged**
