### PR TITLE
Add F32/F64 Equality Logic Yamls for gfx12

### PR DESCRIPTION
**Pull request by wenchuanchen**
same as https://github.com/ROCm/hipBLASLt/pull/1143

### CODE REVIEW

**Comment by wenchuanchen** [comment]
[test.log](https://github.com/user-attachments/files/17124181/test.log)

**Comment by StaceyLai** [comment]
If your commit involves changes to a YAML file, please take note.

Due to PR-1117 (https://github.com/ROCm/hipBLASLt/pull/1117) adding `ActivationType: hipblaslt_all`, all YAML files now need to include the ActivationType field (for hipblaslt logic YAML, use `ActivationType: hipblaslt_all` (not `all`); for tensile test YAML, you can use either `all` or `hipblaslt_all`). 

Correspondingly, in the Logic YAML filename, the `_A` that originally represented `ActivationType: all` should also be changed to `_HA`. These changes have been implemented in PR-1117.

**Comment by wenchuanchen** [comment]
[tox.log](https://github.com/user-attachments/files/17125811/tox.log)
3 failed f8 cases are known issue and not relevant to this PR

**Review by jichangjichang — APPROVED** [review]
lgtm

**Pull request merged**
