### PR TITLE
gfx942_80CU I8I8I TT GridBased

### PR DESCRIPTION
**Pull request by m-kim**
Total number: 6913

### CODE REVIEW

**Review by aazz44ss — DISMISSED** [review]
Please make sure CI passed before merge

**Review by babakpst — DISMISSED** [review]

**Comment by m-kim** [comment]
> Please make sure CI passed before merge

Hi Henry, 942 tests passed and it looks good.

The ubuntu22(main) failed for 90a, which appears to be unrelated to this PR.

**Review by jichangjichang — APPROVED** [review]
Conditional approve
All these PRs already has 2 approvals. If you can confirm these PRs are no risk, you can go ahead to merge it.
We have updated the PR rules. Please must follow it for future PRs.

**Comment by jichangjichang** [comment]
From Mark:
I ran the CI locally and was able to build successfully all four kernels for PR935-PR938 and successfully run python-test and ctests. Please merge the PRs.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
