### PR TITLE
gfx942 80cu HSS/BSS GridBased logic (NN,NT,TN)

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by nakajee** [comment]
hipblaslt-test (no option) passed on gfx942 80cu node.

[==========] 35372 tests from 13 test suites ran. (1789794 ms total)
[  PASSED  ] 35372 tests.
hipBLASLt version: 800

**Review by babakpst — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
lgtm, @nakajee please share how much library size is increased by this PR.

**Comment by nakajee** [comment]
> lgtm, @nakajee please share how much library size is increased by this PR.

Around 900MB increase.
Command: sudo du --max-depth=0 --block-size=M build/release/hipblaslt-install/
Before: 6875M   build/release/hipblaslt-install/
After: 7804M   build/release/hipblaslt-install/

Commit id (before): 9eb8ce5
(gfx942 only (-a gfx942))

**Comment by nakajee** [comment]
Some CI test fail seems unrelated to this change (error at docker stage).
I ran hipblaslt-test on gfx942 node. All passed.

[----------] Global test environment tear-down
[==========] 35886 tests from 13 test suites ran. (1792059 ms total)
[  PASSED  ] 35886 tests.
hipBLASLt version: 1000

command line: ./build/release/clients/staging/hipblaslt-test

**Pull request merged**
