### PR TITLE
Update gfx942 F8F8S TN Equality/GridBased yamls for torch._scaled_mm fix

### PR DESCRIPTION
**Pull request by AndySu12**

### CODE REVIEW

**Comment by AndySu12** [comment]
[SWDEV-505905](https://ontrack-internal.amd.com/browse/SWDEV-505905)

**Review by imcarsonliao — APPROVED** [review]

**Review by aazz44ss — APPROVED** [review]

**Comment by AndySu12** [comment]
[----------] Global test environment tear-down
[==========] 50058 tests from 13 test suites ran. (659906 ms total)
[  PASSED  ] 50055 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] _/matmul_test.matmul/pre_checkin_matmul_extapi_algo_method_tuning_gsu_gemm_only_f16_rf16_rf16_rf16_rf32_r_TN_128_128_65536_1_65536_65536_2_128_128_1_APIExt_APIAlgoIndex_GSU4, where GetParam() = { function: "matmul", name: "matmul_extapi_algo_method_tuning_gsu_gemm_only", category: "pre_checkin", known_bug_platforms: "", alpha: 1, beta: 2, stride_a: 0x24a1308, stride_b: 0x24a1408, stride_c: 0x24a1508, stride_d: 0x24a1608, stride_e: 0x24a1708, user_allocated_workspace: 134217728, M: 0x24a1810, N: 0x24a1910, K: 0x24a1a10, lda: 0x24a1b10, ldb: 0x24a1c10, ldc: 0x24a1d10, ldd: 0x24a1e10, lde: 0x24a1f10, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: -1, requested_solution_num: 1, a_type: f16_r, b_type: f16_r, c_type: f16_r, d_type: f16_r, compute_type: f32_r, compute_input_typeA: non-supported type, compute_input_typeB: non-supported type, scale_type: f32_r, initialization: "rand_int", gpu_arch: "", pad: 4096, grouped_gemm: 0, threads: 0, streams: 0, devices: 
[  FAILED  ] _/matmul_test.matmul/pre_checkin_matmul_extapi_algo_method_tuning_gsu_gemm_only_f16_rf16_rf16_rf16_rf32_r_TN_128_128_65536_1_65536_65536_2_128_128_1_APIExt_APIAlgoIndex_GSU7, where GetParam() = { function: "matmul", name: "matmul_extapi_algo_method_tuning_gsu_gemm_only", category: "pre_checkin", known_bug_platforms: "", alpha: 1, beta: 2, stride_a: 0x24a1308, stride_b: 0x24a1408, stride_c: 0x24a1508, stride_d: 0x24a1608, stride_e: 0x24a1708, user_allocated_workspace: 134217728, M: 0x24a1810, N: 0x24a1910, K: 0x24a1a10, lda: 0x24a1b10, ldb: 0x24a1c10, ldc: 0x24a1d10, ldd: 0x24a1e10, lde: 0x24a1f10, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: -1, requested_solution_num: 1, a_type: f16_r, b_type: f16_r, c_type: f16_r, d_type: f16_r, compute_type: f32_r, compute_input_typeA: non-supported type, compute_input_typeB: non-supported type, scale_type: f32_r, initialization: "rand_int", gpu_arch: "", pad: 4096, grouped_gemm: 0, threads: 0, streams: 0, devices: 
[  FAILED  ] _/matmul_test.matmul/pre_checkin_matmul_extapi_algo_method_tuning_gsu_gemm_only_f16_rf16_rf16_rf16_rf32_r_TN_128_128_65536_1_65536_65536_2_128_128_1_APIExt_APIAlgoIndex_GSU38, where GetParam() = { function: "matmul", name: "matmul_extapi_algo_method_tuning_gsu_gemm_only", category: "pre_checkin", known_bug_platforms: "", alpha: 1, beta: 2, stride_a: 0x24a1308, stride_b: 0x24a1408, stride_c: 0x24a1508, stride_d: 0x24a1608, stride_e: 0x24a1708, user_allocated_workspace: 134217728, M: 0x24a1810, N: 0x24a1910, K: 0x24a1a10, lda: 0x24a1b10, ldb: 0x24a1c10, ldc: 0x24a1d10, ldd: 0x24a1e10, lde: 0x24a1f10, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: -1, requested_solution_num: 1, a_type: f16_r, b_type: f16_r, c_type: f16_r, d_type: f16_r, compute_type: f32_r, compute_input_typeA: non-supported type, compute_input_typeB: non-supported type, scale_type: f32_r, initialization: "rand_int", gpu_arch: "", pad: 4096, grouped_gemm: 0, threads: 0, streams: 0, devices: 

 3 FAILED TESTS
hipBLASLt version: 1200

command line: /opt/rocm/bin/hipblaslt-test

There're 3 failed tests, but not related to F8F8S kernel.

**Comment by AndySu12** [comment]
> [----------] Global test environment tear-down [==========] 50058 tests from 13 test suites ran. (659906 ms total) [ PASSED ] 50055 tests. [ FAILED ] 3 tests, listed below: [ FAILED ] _/matmul_test.matmul/pre_checkin_matmul_extapi_algo_method_tuning_gsu_gemm_only_f16_rf16_rf16_rf16_rf32_r_TN_128_128_65536_1_65536_65536_2_128_128_1_APIExt_APIAlgoIndex_GSU4, where GetParam() = { function: "matmul", name: "matmul_extapi_algo_method_tuning_gsu_gemm_only", category: "pre_checkin", known_bug_platforms: "", alpha: 1, beta: 2, stride_a: 0x24a1308, stride_b: 0x24a1408, stride_c: 0x24a1508, stride_d: 0x24a1608, stride_e: 0x24a1708, user_allocated_workspace: 134217728, M: 0x24a1810, N: 0x24a1910, K: 0x24a1a10, lda: 0x24a1b10, ldb: 0x24a1c10, ldc: 0x24a1d10, ldd: 0x24a1e10, lde: 0x24a1f10, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: -1, requested_solution_num: 1, a_type: f16_r, b_type: f16_r, c_type: f16_r, d_type: f16_r, compute_type: f32_r, compute_input_typeA: non-supported type, compute_input_typeB: non-supported type, scale_type: f32_r, initialization: "rand_int", gpu_arch: "", pad: 4096, grouped_gemm: 0, threads: 0, streams: 0, devices: [ FAILED ] _/matmul_test.matmul/pre_checkin_matmul_extapi_algo_method_tuning_gsu_gemm_only_f16_rf16_rf16_rf16_rf32_r_TN_128_128_65536_1_65536_65536_2_128_128_1_APIExt_APIAlgoIndex_GSU7, where GetParam() = { function: "matmul", name: "matmul_extapi_algo_method_tuning_gsu_gemm_only", category: "pre_checkin", known_bug_platforms: "", alpha: 1, beta: 2, stride_a: 0x24a1308, stride_b: 0x24a1408, stride_c: 0x24a1508, stride_d: 0x24a1608, stride_e: 0x24a1708, user_allocated_workspace: 134217728, M: 0x24a1810, N: 0x24a1910, K: 0x24a1a10, lda: 0x24a1b10, ldb: 0x24a1c10, ldc: 0x24a1d10, ldd: 0x24a1e10, lde: 0x24a1f10, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: -1, requested_solution_num: 1, a_type: f16_r, b_type: f16_r, c_type: f16_r, d_type: f16_r, compute_type: f32_r, compute_input_typeA: non-supported type, compute_input_typeB: non-supported type, scale_type: f32_r, initialization: "rand_int", gpu_arch: "", pad: 4096, grouped_gemm: 0, threads: 0, streams: 0, devices: [ FAILED ] _/matmul_test.matmul/pre_checkin_matmul_extapi_algo_method_tuning_gsu_gemm_only_f16_rf16_rf16_rf16_rf32_r_TN_128_128_65536_1_65536_65536_2_128_128_1_APIExt_APIAlgoIndex_GSU38, where GetParam() = { function: "matmul", name: "matmul_extapi_algo_method_tuning_gsu_gemm_only", category: "pre_checkin", known_bug_platforms: "", alpha: 1, beta: 2, stride_a: 0x24a1308, stride_b: 0x24a1408, stride_c: 0x24a1508, stride_d: 0x24a1608, stride_e: 0x24a1708, user_allocated_workspace: 134217728, M: 0x24a1810, N: 0x24a1910, K: 0x24a1a10, lda: 0x24a1b10, ldb: 0x24a1c10, ldc: 0x24a1d10, ldd: 0x24a1e10, lde: 0x24a1f10, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: -1, requested_solution_num: 1, a_type: f16_r, b_type: f16_r, c_type: f16_r, d_type: f16_r, compute_type: f32_r, compute_input_typeA: non-supported type, compute_input_typeB: non-supported type, scale_type: f32_r, initialization: "rand_int", gpu_arch: "", pad: 4096, grouped_gemm: 0, threads: 0, streams: 0, devices:
> 
> 3 FAILED TESTS hipBLASLt version: 1200
> 
> command line: /opt/rocm/bin/hipblaslt-test
> 
> There're 3 failed tests, but not related to F8F8S kernel.

Someone is using GPU, hence caused OOM. I will launch hipblaslt-test again.

**Comment by AndySu12** [comment]
After switching back to develop branch 0ed9795b44579c98218bcdf20cf3f41aa5e622b9, I still encounter the same gtest error. So it should not be related to this F8F8S PR, let's merge it now.

**Pull request merged**
