### PR TITLE
reduce default gfx targets (#1311)

### PR DESCRIPTION
**Pull request by TorreZuk**
* remove non production gfx

### CODE REVIEW

**Comment by TorreZuk** [comment]
@hcman2 and @jichangjichang can you review this PR same as previous to develop as trying to fast track it.  Thanks

**Review by jichangjichang — APPROVED** [review]

**Comment by jichangjichang** [comment]
@TorreZuk  will you follow cherry-pick process for 6.3 RC?

**Comment by TorreZuk** [comment]
> @TorreZuk will you follow cherry-pick process for 6.3 RC?

Yes.  Still not clear if it will be allowed in. I will create doc for process

**Comment by TorreZuk** [comment]
@hcman2 or @KKyang second approval required...

**Comment by jichangjichang** [comment]
> @hcman2 or @KKyang second approval required...

@TorreZuk 
We don't need second approval for RC branch. To be more precise, the final approval is always from release PM. And only release PM can merge the PR once cherry-pick process is approved.

**Pull request merged**
