### PR TITLE
Tune aquavanjaram942 80cu HHS and BBS NN memory bound GEMM sizes

### PR DESCRIPTION
**Pull request by aferoz21**
HHS NN Memory bound GEMM sizes from this ticket SWDEV-460608
- This covers only M and N flipped. 33 GEMM sizes. 
- Improvement of ~64% from base version .

### CODE REVIEW

**Comment by nakajee** [comment]
I am not sure what is wrong but the same fail did not happen in my PR #816.
Probably better to re-run CI test, or try the same test on your local node.

**Comment by aferoz21** [comment]
> I am not sure what is wrong but the same fail did not happen in my PR #816. Probably better to re-run CI test, or try the same test on your local node.

Thanks. I am noticing the same failure in previous PR from yours . I will re-run.

**Comment by nakajee** [comment]
> > I am not sure what is wrong but the same fail did not happen in my PR #816. Probably better to re-run CI test, or try the same test on your local node.
> 
> Thanks. I am noticing the same failure in previous PR from yours . I will re-run.

The link error was same, but there was another error in unit test in your PR (which did not happen in my PR)

**Review by nakajee — APPROVED** [review]
OK. 942 unit test passed this time (ignoring link error (happening in other PRs)).
Perf improvement looks good.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
