### PR TITLE
Added F8HS / HHS TN Equality kernels for gfx942

### PR DESCRIPTION
**Pull request by pkamd**
Added 4 sizes for F8HS / HHS TN for aquavanjaram942 in Equality folder.

### CODE REVIEW

**Comment by nakajee** [comment]
Would you double-check the norm_check value of 1x6144x8192?

**Comment by nakajee** [comment]
> Would you double-check the norm_check value of 1x6144x8192?

This seems to be OK. I checked wrong place....
The change itself looks good.
Please run CI test (hipblaslt-test) locally.

**Review by babakpst — APPROVED** [review]

**Comment by pkamd** [comment]
ran hipblaslt-test locally & all tests passed
```
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 37294 tests from 13 test suites ran. (1885045 ms total)
[  PASSED  ] 37294 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test
```

**Review by nakajee — APPROVED** [review]
Thanks for your confirmation.
Looks good.
CI fails seems unrelated to this change.

**Comment by babakpst** [comment]
@jichangjichang Please review this PR. Thanks.

**Review by jichangjichang — APPROVED** [review]
lgtm

**Pull request merged**
