### PR TITLE
bug fix, correct typo in previous host validation commit

### PR DESCRIPTION
**Pull request by cmingch**

### CODE REVIEW

**Review by KKyang — CHANGES_REQUESTED** [review]
Can you move the for loop into the if else condition?

**Review by jichangjichang — CHANGES_REQUESTED** [review]
Add some basic fp16 scaleVector tests for all transpose

**Comment by cmingch** [comment]
> Can you move the for loop into the if else condition?

done

**Review by KKyang — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]

**Comment by jichangjichang** [comment]
Please add basic FP16 SAV support and test in the future PR.
@Jinp800125

**Pull request merged**
