### PR TITLE
gtest fix for int8_matmul

### PR DESCRIPTION
**Pull request by AndySu12**
- Add new function saturate_cast with docstring
- Fix cblas_gemm and epilogue_func
- Add more test cases for precision int8

### CODE REVIEW

**Review by jichangjichang — CHANGES_REQUESTED** [review]
you should enlarge the size but not make this issue invisible.
The solution should be making the CPU cast formula same with GPU cast formula

**Comment by AndySu12** [comment]
> you should enlarge the size but not make this issue invisible. The solution should be making the CPU cast formula same with GPU cast formula

Done.

**Review by KKyang — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
lgtm

**Comment by AndySu12** [comment]
gfx942 local test passed.
---------------------------
hipBLASLt version: 800

Query device success: there are 8 devices
-------------------------------------------------------------------------------
Device ID 0 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 1 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 2 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 3 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 4 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 5 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 6 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
Device ID 7 : AMD Instinct MI300X gfx942:sramecc+:xnack-
with 206.1 GB memory, max. SCLK 2100 MHz, max. MCLK 1300 MHz, compute capability 9.4
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------
info: parsing of test data may take a couple minutes before any test output appears...

Note: Google Test filter = *dst_i8*
[==========] Running 64 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 64 tests from _/matmul_test
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_0_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_0_128_128_1 (13378 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_0_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_0_128_128_1_SAV (67 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_2_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_2_128_128_1 (65 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_2_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_128_128_128_1_128_128_2_128_128_1_SAV (66 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_0_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_0_131_131_1 (67 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_0_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_0_131_131_1_SAV (66 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_2_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_2_131_131_1 (65 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_2_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_131_131_131_1_131_131_2_131_131_1_SAV (66 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_0_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_0_1024_1024_1 (652 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV (625 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_2_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_2_1024_1024_1 (598 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV (598 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_0_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_0_1031_1031_1 (598 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV (623 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_2_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_2_1031_1031_1 (592 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NN_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV (596 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_0_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_0_128_128_1 (27 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_0_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_0_128_128_1_SAV (27 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_2_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_2_128_128_1 (27 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_2_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_128_128_128_1_128_128_2_128_128_1_SAV (34 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_0_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_0_131_131_1 (28 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_0_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_0_131_131_1_SAV (41 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_2_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_2_131_131_1 (27 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_2_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_131_131_131_1_131_131_2_131_131_1_SAV (27 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_0_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_0_1024_1024_1 (833 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV (830 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_2_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_2_1024_1024_1 (801 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV (810 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_0_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_0_1031_1031_1 (843 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV (811 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_2_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_2_1031_1031_1 (826 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_NT_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV (854 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_0_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_0_128_128_1 (33 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_0_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_0_128_128_1_SAV (25 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_2_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_2_128_128_1 (25 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_2_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_128_128_128_1_128_128_2_128_128_1_SAV (24 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_0_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_0_131_131_1 (33 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_0_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_0_131_131_1_SAV (33 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_2_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_2_131_131_1 (25 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_2_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_131_131_131_1_131_131_2_131_131_1_SAV (31 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_0_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_0_1024_1024_1 (1048 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV (1074 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_2_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_2_1024_1024_1 (1056 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV (1070 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_0_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_0_1031_1031_1 (1067 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV (1104 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_2_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_2_1031_1031_1 (1064 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TN_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV (1101 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_0_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_0_128_128_1 (31 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_0_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_0_128_128_1_SAV (28 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_2_128_128_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_2_128_128_1 (26 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_2_128_128_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_128_128_128_1_128_128_2_128_128_1_SAV (36 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_0_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_0_131_131_1 (25 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_0_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_0_131_131_1_SAV (28 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_2_131_131_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_2_131_131_1 (31 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_2_131_131_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_131_131_131_1_131_131_2_131_131_1_SAV (24 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_0_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_0_1024_1024_1 (3404 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_0_1024_1024_1_SAV (3444 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_2_1024_1024_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_2_1024_1024_1 (3423 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1024_1024_1024_1_1024_1024_2_1024_1024_1_SAV (3437 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_0_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_0_1031_1031_1 (1068 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_0_1031_1031_1_SAV (1080 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_2_1031_1031_1
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_2_1031_1031_1 (1056 ms)
[ RUN      ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV
[       OK ] _/matmul_test.matmul/pre_checkin_matmul_gemm_i8_dst_i8_94x_i8_ri8_ri8_ri8_ri32_r_relu_TT_1031_1031_1031_1_1031_1031_2_1031_1031_1_SAV (1105 ms)
[----------] 64 tests from _/matmul_test (52666 ms total)

[----------] Global test environment tear-down
[==========] 64 tests from 1 test suite ran. (52668 ms total)
[  PASSED  ] 64 tests.
hipBLASLt version: 800

command line: ./clients/staging/hipblaslt-test --gtest_filter=*dst_i8*

**Pull request merged**
