### PR TITLE
Tune Aquavanjaram942 Grid sizes for BBS NN

### PR DESCRIPTION
**Pull request by pkamd**
Updated 8 grid points to address perf tuning request.
Ensure changes doesn't degrade existing grid point performance.

Note - Same changes as old PR.

### CODE REVIEW

**Comment by pkamd** [comment]
All hipBLASLt tests passed -
```
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (2234494 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test
```

**Review by nakajee — DISMISSED** [review]
Looks good

**Review by KKyang — DISMISSED** [review]

**Review by KKyang — DISMISSED** [review]

**Review by nakajee — DISMISSED** [review]

**Comment by StaceyLai** [comment]
If your commit involves changes to a YAML file, please take note.

Due to PR-1117 (https://github.com/ROCm/hipBLASLt/pull/1117) adding `ActivationType: hipblaslt_all`, all YAML files now need to include the `ActivationType` field (for hipblaslt logic YAML, use `ActivationType: hipblaslt_all` (not `all`); for tensile test YAML, you can use either `all` or `hipblaslt_all`). 

Correspondingly, in the Logic YAML filename, the `_A` that originally represented `ActivationType: all` should also be changed to `_HA`. These changes have been implemented in PR-1117.

**Comment by nakajee** [comment]
I removed noCI label.

**Comment by pkamd** [comment]
```
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (2371439 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test
```

**Review by aazz44ss — APPROVED** [review]

**Review by nakajee — APPROVED** [review]
CI test result looks good.
No fail in gfx942.

**Pull request merged**
