### PR TITLE
Tune Aquavanjaram942 Grid sizes for BBS NN

### PR DESCRIPTION
**Pull request by pkamd**
Updated 8 grid points to address perf tuning request. 
Ensure changes doesn't degrade existing grid point performance.

### CODE REVIEW

**Comment by jichangjichang** [comment]
If this PR is necessary for 6.3, please remember file PR to release-staging/rocm-rel-6.3 as well.

**Comment by nakajee** [comment]
Please run hipblaslt-test on your local node (with the change) and paste the result here if you put noCI label.

**Comment by pkamd** [comment]
All hipBLASLt tests passed -
```
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (2234494 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

command line: ./hipblaslt-test
```

**Comment by nakajee** [comment]
Don't we need to cover HHS?

**Comment by pkamd** [comment]
> Don't we need to cover HHS?

Yes the request is for both HHS and BBS. Planning to address it as a separate PR.

**Pull request closed without merging**
