### PR TITLE
Fix UnrollLoopSwapGlobalReadOrder=1 bug for small GRVW.

### PR DESCRIPTION
**Pull request by hcman2**
1. The GRVWA/B index may jump in different way.
We cannot re-use the G2L VGPRs if index mismatched.

2. If G2LA/B has bubble. The index is incorrect when swapAB.

### CODE REVIEW

**Comment by hcman2** [comment]
image
This is an example that the G2LA/B vgpr index jump in different way.

**Comment by hcman2** [comment]
gfx94x tox passed

**Review by aazz44ss — DISMISSED** [review]

**Comment by hcman2** [comment]
[----------] Global test environment tear-down
[==========] 50058 tests from 13 test suites ran. (1611023 ms total)
[  PASSED  ] 50058 tests.
hipBLASLt version: 1200

**Comment by hcman2** [comment]
Note that this is timing issue. If you have timing issue with UnrollLoopSwapGlobalReadOrder=1. You may check whether your kernel is relative to this PR.

**Comment by hcman2** [comment]
tox passed again.
=========== 79 passed, 37 skipped, 3 warnings in 9728.35s (2:42:08) ============

**Review by ssuyuanchang — APPROVED** [review]

**Review by KKyang — APPROVED** [review]

**Pull request merged**
