### PR TITLE
Aquavanjaram942X BBS TN GEMM sizes tuned

### PR DESCRIPTION
**Pull request by aferoz21**
BBS TN GEMM sizes tuned and 15% improvement done in the weighted average.

### CODE REVIEW

**Comment by aferoz21** [comment]
./hipBLAS-test

[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (656117 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

**Comment by nakajee** [comment]
We do not need to use "noCI" label

**Review by aazz44ss — APPROVED** [review]
LGTM

**Review by nakajee — APPROVED** [review]
Looks good

**Pull request merged**
