### PR TITLE
Update gfx942 NT/TN/NN FP8/BF8/BF16 Equality

### PR DESCRIPTION
**Pull request by geotseng-amd**
1, Ticket: https://ontrack-internal.amd.com/browse/SWDEV-502660

### CODE REVIEW

**Review by jichangjichang — COMMENTED** [review]
Only F8 or BF8 input needs Scale A/B

**Comment by geotseng-amd** [comment]
> Only F8 or BF8 input needs Scale A/B

done

**Review by KKyang — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
update PR title for the problem type 
example:[Update gfx942_80cu NT/TN/NN f16/f32 Equality (](https://github.com/ROCm/hipBLASLt/commit/b61a09590ee8f437055086f29156c704a68f6385)https://github.com/ROCm/hipBLASLt/pull/1452[)](https://github.com/ROCm/hipBLASLt/commit/b61a09590ee8f437055086f29156c704a68f6385)

**Comment by geotseng-amd** [comment]
All the local CI tests were passed.


[0;32m[----------] [mGlobal test environment tear-down
[0;32m[==========] [m50058 tests from 13 test suites ran. (2350152 ms total)
[0;32m[  PASSED  ] [m50058 tests.
hipBLASLt version: 1200

command line: ./build/release/clients/staging/hipblaslt-test --gtest_output=xml --gtest_color=yes --gtest_repeat=1

**Pull request merged**
