### PR TITLE
gfx942 NN GridBased

### PR DESCRIPTION
**Pull request by Jinp800125**
Pass CI test
4aaba9b2231f087f20bb694cbdf7b71f8d19ee1a + 1,1,1,1 grid point

### CODE REVIEW

**Comment by jichangjichang** [comment]
@Jinp800125 Do we know why PR#993 cause some tests fail?

**Comment by aazz44ss** [comment]
> @Jinp800125 Do we know why PR#993 cause some tests fail?

It didn't have GRVWA1 kernel for M=1 cases

**Review by aazz44ss — APPROVED** [review]

**Review by jichangjichang — APPROVED** [review]
lgtm

**Comment by Jinp800125** [comment]
local run hipblaslt test PASSED due to tox had 8r_amaxd.yaml validation  fail
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 35886 tests from 13 test suites ran. (1644452 ms total)
[  PASSED  ] 35886 tests.
hipBLASLt version: 1000

**Pull request merged**
