### PR TITLE
Optimize ds read waitcnt for 1st iteration.

### PR DESCRIPTION
**Pull request by hcman2**
Originally, we will always wait all of the PLR to be done in 1st iteration.
This optimization separates it into 2 waitcnt. It will release the pressure if the kernel is blocked by the 1st waitcnt.

### CODE REVIEW

**Comment by hcman2** [comment]
image

This is just an example.

**Comment by hcman2** [comment]
CI gfx94x Ubuntu pass.

**Comment by hcman2** [comment]
---- generated xml file: /meng/hcman/hipBLASLt/tensilelite/python_tests.xml ----
========== 23 passed, 83 skipped, 372 warnings in 2019.89s (0:33:39) ===========
local gfx90a passed

**Review by KKyang — APPROVED** [review]

**Review by aazz44ss — APPROVED** [review]
LGTM

**Pull request merged**
