### PR TITLE
Tune Aquavanjaram942 HHS NN TN NT GEMM sizes equality and grid based

### PR DESCRIPTION
**Pull request by aferoz21**
1) Tuned HHS TN, NN, NT GEMM sizes with ~17% improvement.
2) 2 Grid point sizes updated and 8 equality size kernels added.

### CODE REVIEW

**Comment by aferoz21** [comment]
hiPBLAS-test results

[----------] 1 test from ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest.amaxFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest.amaxFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxUnsupportedDatatypeTest (0 ms total)

[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest
[ RUN      ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0
[       OK ] ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest.amaxWithScaleFailureUnsupportedDatatype/0 (0 ms)
[----------] 1 test from ExtOpTest/ExtOpAMaxWithScaleUnsupportedDatatypeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (1419771 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1000

**Review by KKyang — DISMISSED** [review]

**Comment by aferoz21** [comment]
Thanks Koji ! added 1 more grid size kernel that was missed. Also verify log updated with trig_float init.

**Review by nakajee — APPROVED** [review]
Looks good.

**Comment by nakajee** [comment]
@KKyang 
Please check this PR again.
Thanks.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
