### PR TITLE
gfx942 80cu XFP32 GridBased tuning (NN,NT,TN,TT)

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by vin-huang** [comment]
The definition of UseScaleAlphaVec has been changed as below, please kindly modified your YAML file accordingly.

UseScaleAlphaVec=False -> UseScaleAlphaVec=0

UseScaleAlphaVec=True -> UseScaleAlphaVec=1

Redefined UseScaleAlphaVec
0 - Alpha Vector Scaling is disabled
1 - Calculated Alpha Vector Scaling along M-dim
2 - Calculated Alpha Vector Scaling along N-dim
3 - Calculated Alpha Vector Scaling along either M-dim or N-dim.

**Comment by nakajee** [comment]
> The definition of UseScaleAlphaVec has been changed as below, please kindly modified your YAML file accordingly.
> 
> UseScaleAlphaVec=False -> UseScaleAlphaVec=0
> 
> UseScaleAlphaVec=True -> UseScaleAlphaVec=1
> 
> Redefined UseScaleAlphaVec 0 - Alpha Vector Scaling is disabled 1 - Calculated Alpha Vector Scaling along M-dim 2 - Calculated Alpha Vector Scaling along N-dim 3 - Calculated Alpha Vector Scaling along either M-dim or N-dim.

Thanks for letting me know.
Updated.

**Comment by nakajee** [comment]
Merged latest develop and converted UseScaleAB to "".

**Review by babakpst — APPROVED** [review]

**Comment by babakpst** [comment]
@vin-huang can you please review this PR? Thanks.

**Comment by nakajee** [comment]
Some error in ubuntu22 & gfx942 at docker stage.
I do not think my change causes any issue at docker stage.
Most likely unrelated to my change.

**Comment by nakajee** [comment]
One gfx942 precheckin test failed.
pre_checkin_matmul_real_1b_dst_f8_amaxD_bf8_rf8_rf8_rf8_rf32_r_relu_TT_127_129_127_1_127_129_0_127_127_1_SA_SB_SD_AMaxD

This is f8 case. It is unlikely related to this change.

**Comment by KKyang** [comment]
Try rebasing locally and run hipblaslt-test with filter to see if it still fails

**Comment by nakajee** [comment]
> Try rebasing locally and run hipblaslt-test with filter to see if it still fails

I tried it locally and it passed.

[  PASSED  ] 35002 tests.
hipBLASLt version: 800

command line: ./build/release/clients/staging/hipblaslt-test --gtest_output=xml --gtest_color=yes --gtest_filter=*

**Comment by nakajee** [comment]
Hi @KKyang 
CI test finally passed after merging the latest develop commits.
Do you have any more comments?

**Comment by KKyang** [comment]
No, thanks.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
