### PR TITLE
Update ActivationFuncCall in F16/BF16 gfx942_80CU libraries

### PR DESCRIPTION
**Pull request by babakpst**
To reduce the size of the library, ActivationFuncCall: false -> true.

### CODE REVIEW

**Review by nakajee — COMMENTED** [review]
The change looks OK.
CI test errors seem not related to this change.
We need to wait for the fix for CI test error.

**Comment by jichangjichang** [comment]
@babakpst  you can run the tests (Tests in PR rules) with your PR. If result are all pass, you can just comment it here.

**Comment by KKyang** [comment]
> The change looks OK. CI test errors seem not related to this change. We need to wait for the fix for CI test error.

Both CI are down. Please run local tests. Although CI test errors seem not related to this change, you still can't guarantee that CI will definitely pass.

**Comment by babakpst** [comment]
I am running the verifications in parallel, I will get to the tests next.

**Review by nakajee — APPROVED** [review]
Looks good.
Precheckin test fail on gfx11 and 90a seems not related to this change (i8_gsu.yaml failed)

**Comment by KKyang** [comment]
Do we still need this? @nakajee  mentioned in the other PR. @babakpst

**Comment by KKyang** [comment]
Oh, they're different.

**Comment by jichangjichang** [comment]
> Looks good. Precheckin test fail on gfx11 and 90a seems not related to this change (i8_gsu.yaml failed)

rebase https://github.com/babakpst/hipBLASLt/tree/HB_activation to latest develop can make the test pass.

**Review by jichangjichang — APPROVED** [review]
lgtm

**Pull request merged**
