### PR TITLE
Bug fix in stream-k tile assignment

### PR DESCRIPTION
**Pull request by AlexBrownAMD**
Fixes a bug in tile assignment when running dynamic grid mode.

### CODE REVIEW

**Comment by nakajee** [comment]
Can we add a test case to trigger this issue?

**Comment by AlexBrownAMD** [comment]
> Can we add a test case to trigger this issue?

I'm looking into how I could add a test case for it. It would require setting an environment variable to enable dynamic grid mode, which I'm not sure if we can do currently in the python tests.

**Review by nakajee — APPROVED** [review]
Thanks for your comment.
It is probably difficult to set some specific env variable for unit test.
OK for now.

**Review by neoblizz — APPROVED** [review]

**Review by nakajee — APPROVED** [review]
Looks good.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
