### PR TITLE
Add Navi32 TN_BBS/NN_BBS Kernels

### PR DESCRIPTION
**Pull request by wenchuanchen**
tuning requests:
https://ontrack-internal.amd.com/browse/SWDEV-480801
https://ontrack-internal.amd.com/browse/SWDEV-480799

### CODE REVIEW

**Review by jichangjichang — COMMENTED** [review]
Does this exact tuning request need epilogue?

**Comment by wenchuanchen** [comment]
This tuning request doesn't need epilogue. But in order to reduce the number of logic yaml files, we keep the type as less as we  can. Also, logic yaml with epilogue can be applied to problem without epilogue.

**Comment by wenchuanchen** [comment]
gtest on gfx1101
[gtest.log](https://github.com/user-attachments/files/17469806/gtest.log)

**Comment by wenchuanchen** [comment]
tox on gfx1101
[tox.log](https://github.com/user-attachments/files/17470013/tox.log)

**Review by jichangjichang — APPROVED** [review]

**Review by cmingch — APPROVED** [review]

**Pull request merged**
