### PR TITLE
fix incorrect calcLdsNumBytes calculation

### PR DESCRIPTION
**Pull request by aazz44ss**
fix incorrect ldsPad value in calcLdsNumBytes

### CODE REVIEW

**Review by KKyang — APPROVED** [review]

**Comment by hcman2** [comment]
CI Failed.
mci/precheckin/test/gfx90a(main) — Failed in Test stage on gfx90a

**Comment by aazz44ss** [comment]
> CI Failed. mci/precheckin/test/gfx90a(main) — Failed in Test stage on gfx90a

Re-run CI again, it passed.

**Review by hcman2 — APPROVED** [review]
OK if gfx94x ci also pass.

**Comment by hcman2** [comment]
Should we add a test yaml to cover this bug?

**Comment by aazz44ss** [comment]
> Should we add a test yaml to cover this bug?

I just re-ran CI and it passed. Not sure what happened.

**Comment by hcman2** [comment]
Not sure which bug this change fixed? if we have bug before this change, the test yaml in this codebase cannot hit the bug this change fixed. That is why I ask for a test yaml to hit this bug.

**Comment by aazz44ss** [comment]
> Not sure which bug this change fixed? if we have bug before this change, the test yaml in this codebase cannot hit the bug this change fixed. That is why I ask for a test yaml to hit this bug.

OK, I misunderstood I thought you were saying CI failed bug, that's what I an not sure, I re-ran CI and it passed, I also check CI on my local gfx942 and passed.

This PR fix wrong value used in the function, not able to reproduce after fix.

**Pull request merged**
