### PR TITLE
Cherry-pick to release/rocm-rel-6.3: Clarify release and version number for 6.3.0 (#1255)

### PR DESCRIPTION
**Pull request by amd-jnovotny**
(cherry picked from commit abf820fba9ef2f638968ef3b05f74ed79b9dd02b)

### CODE REVIEW

**Review by jichangjichang — APPROVED** [review]

**Comment by jichangjichang** [comment]
@amd-jnovotny  will you follow cherry-pick request?

**Comment by amd-jnovotny** [comment]
@jichangjichang Thanks for the approval. I don't have merge authorization here, so one of your team will have to merge. I could also ask Sam, but he's out of the office until next week.

**Comment by amd-jnovotny** [comment]
@jichangjichang I think I might have misunderstood your comment. Do I need to place this PR on an official list for cherry-picks for the release. I'm still familiarizing myself with the process for each component, so sorry for any confusion. Thanks for any info.

**Comment by vamovsik** [comment]
Fix for https://ontrack-internal.amd.com/browse/SWDEV-495487

**Pull request merged**
