### PR TITLE
Fix CI gfx11 I8 Fail - Add Local Read waitcnt for ScaleAlphaVec

### PR DESCRIPTION
**Pull request by wenchuanchen**
Fix CI gfx11 I8 Fail - Add Local Read waitcnt for ScaleAlphaVec

### CODE REVIEW

**Review by KKyang — APPROVED** [review]

**Review by KKyang — CHANGES_REQUESTED** [review]
Remove L997-1003

**Review by KKyang — APPROVED** [review]

**Comment by wenchuanchen** [comment]
hipblaslt-test and tox on gfx1101:
[test.log](https://github.com/user-attachments/files/17183305/test.log)
[tox.log](https://github.com/user-attachments/files/17183304/tox.log)

**Comment by wenchuanchen** [comment]
gtest on gfx942
[gtest.log](https://github.com/user-attachments/files/17230015/gtest.log)

**Comment by wenchuanchen** [comment]
tox on gfx942
[tox.log](https://github.com/user-attachments/files/17240953/tox.log)

**Review by cmingch — APPROVED** [review]

**Pull request merged**
