### PR TITLE
Tune aquavanjaram942 I8I8I TN memory bound GEMM sizes for CU80

### PR DESCRIPTION
**Pull request by aferoz21**
1) I8I8I type (ie a_type: i8_r, b_type: i8_r, c_type: i8_r, d_type: i8_r, compute_type: c_i32_r).
2) This PR covers INT8 (TN), memory bound tests alone (33 GEMM sizes). 
3) Significant improvement achieved as an average of 450%.

### CODE REVIEW

**Comment by nakajee** [comment]
Please run merge.py (merge same file) to remove lda,b,c,d.

**Comment by nakajee** [comment]
Did you try LSU2,4? Did LSU1 always win?

**Comment by aferoz21** [comment]
> Please run merge.py (merge same file) to remove lda,b,c,d.

Yes removed the lda,b,c,d.

**Comment by aferoz21** [comment]
> Did you try LSU2,4? Did LSU1 always win?
yes I tried LSU 2 and LSU4 in one of the config file. LSU 1 wins.

**Comment by nakajee** [comment]
> > Did you try LSU2,4? Did LSU1 always win?
> > yes I tried LSU 2 and LSU4 in one of the config file. LSU 1 wins.

OK. Looks like LSU+INT8 is rejected.
We need to enable it, but it is ok for now.

**Review by nakajee — APPROVED** [review]
Looks good

**Review by KKyang — APPROVED** [review]

**Review by babakpst — APPROVED** [review]

**Pull request merged**
