### PR TITLE
GFX942 equality tuning for F8HS and F8B8HS for TN,NT,NN

### PR DESCRIPTION
**Pull request by smalekta**
Adding new kernels/equality libraries for F8HS+F8B8HS for TN,NT,NN with bias

### CODE REVIEW

**Comment by smalekta** [comment]
(Supporting files will be uploaded) Tests are passing 

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (642284 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1100

**Comment by smalekta** [comment]
reduced the number of added/changed libraries to only with bias. They can handle both with and without bias case with minimal perf difference according to our data

**Comment by smalekta** [comment]
(On the latest commit in the PR)

[----------] Global test environment tear-down
[==========] 48206 tests from 13 test suites ran. (453950 ms total)
[  PASSED  ] 48206 tests.
hipBLASLt version: 1100

**Review by babakpst — APPROVED** [review]

**Comment by jichangjichang** [comment]
> reduced the number of added/changed libraries to only with bias. They can handle both with and without bias case with minimal perf difference according to our data

If so, please revise PR title accordingly

**Review by jichangjichang — APPROVED** [review]

**Pull request merged**
