### PR TITLE
Add gfx941/942 NN fp32 yamls for large m size

### PR DESCRIPTION
**Pull request by AndySu12**
JIRA: [SWDEV-444316](https://ontrack-internal.amd.com/browse/SWDEV-444316)

### CODE REVIEW

**Comment by AndySu12** [comment]
CI: http://math-ci.amd.com/blue/organizations/jenkins/gfx94x%2Fprecheckin%2FhipBLASLt/detail/PR-637/4/pipeline

**Comment by jichangjichang** [comment]
problem's N size is 32 which is larger enough to use MI16x16 or MI32x32. I am curious that have you tried both MI16x16 and MI4x4? And MI4x4 is the winner?

**Comment by AndySu12** [comment]
> problem's N size is 32 which is larger enough to use MI16x16 or MI32x32. I am curious that have you tried both MI16x16 and MI4x4? And MI4x4 is the winner?

I also have tried MI16x16 and MI32x32 with minimum macro tiles, but encounter BufferStoreOffsetLimitCheck errors like below.
`BufferStoreOffsetLimitCheck(MT1:16): (67108864 * 4 * 16 < 4294967296)`
`BufferStoreOffsetLimitCheck(MT1:32): (67108864 * 4 * 32 < 4294967296)`
It shows that MT1 should be less than 16, which implies MI4x4 is the one and only choice. Therefore, I decide to use MT1=8.
After tuning, the final solution is MT256x8x8 with MI4x4.

**Comment by jichangjichang** [comment]
> BufferStoreOffsetLimitCheck

got it

**Comment by jichangjichang** [comment]
> > problem's N size is 32 which is larger enough to use MI16x16 or MI32x32. I am curious that have you tried both MI16x16 and MI4x4? And MI4x4 is the winner?
> 
> I also have tried MI16x16 and MI32x32 with minimum macro tiles, but encounter BufferStoreOffsetLimitCheck errors like below. `BufferStoreOffsetLimitCheck(MT1:16): (67108864 * 4 * 16 < 4294967296)` `BufferStoreOffsetLimitCheck(MT1:32): (67108864 * 4 * 32 < 4294967296)` It shows that MT1 should be less than 16, which implies MI4x4 is the one and only choice. Therefore, I decide to use MT1=8. After tuning, the final solution is MT256x8x8 with MI4x4.

BufferStoreOffsetLimitCheck simpy use MT1 as the max offset size as the upper limitation, which was wrong. Different kernel parameters would make the max offset size different. For example, you can use MI32x32 kernel with sourceswap with MT1=32, which can solve this problem size and produce correct results, if you remove the checking of BufferLoadOffsetLimitCheck_Beta() and BufferStoreOffsetLimitCheck().

**Review by jichangjichang — APPROVED** [review]
BufferStoreOffsetLimitCheck checking can be revised by another PR.
This PR can be a shorterm solution for your ticket.

Another thing is that you should squash your commit into one. There are already 7 commits in your PR, and most of them are empty

**Comment by AndySu12** [comment]
> > > problem's N size is 32 which is larger enough to use MI16x16 or MI32x32. I am curious that have you tried both MI16x16 and MI4x4? And MI4x4 is the winner?
> > 
> > 
> > I also have tried MI16x16 and MI32x32 with minimum macro tiles, but encounter BufferStoreOffsetLimitCheck errors like below. `BufferStoreOffsetLimitCheck(MT1:16): (67108864 * 4 * 16 < 4294967296)` `BufferStoreOffsetLimitCheck(MT1:32): (67108864 * 4 * 32 < 4294967296)` It shows that MT1 should be less than 16, which implies MI4x4 is the one and only choice. Therefore, I decide to use MT1=8. After tuning, the final solution is MT256x8x8 with MI4x4.
> 
> BufferStoreOffsetLimitCheck simpy use MT1 as the max offset size as the upper limitation, which was wrong. Different kernel parameters would make the max offset size different. For example, you can use MI32x32 kernel with sourceswap with MT1=32, which can solve this problem size and produce correct results, if you remove the checking of BufferLoadOffsetLimitCheck_Beta() and BufferStoreOffsetLimitCheck().

Thanks @jichangjichang, the formulas in BufferLoadOffsetLimitCheck_Beta and BufferStoreOffsetLimitCheck should be updated, I will investigate and make another PR to fix.

**Comment by AndySu12** [comment]
> BufferStoreOffsetLimitCheck checking can be revised by another PR. This PR can be a shorterm solution for your ticket.
> 
> Another thing is that you should squash your commit into one. There are already 7 commits in your PR, and most of them are empty

Will squash these.

**Review by TonyYHsieh — APPROVED** [review]
LGTM

**Pull request merged**
