### PR TITLE
Support Azure Linux 3.x

### PR DESCRIPTION
**Pull request by Serge45**
## Brief ##
This PR amends compatibility issues for Azure Linux 3.x, ticket: SWDEV-475885.

## Implementation ##
 - [x] Made `install.sh` support Azure Linux
 - [x] Set C++ standard to 17 due to compatibility issue of libstdc++ 13.2 and clang 17+ HIP front-end, refer to [GCC](https://github.com/gcc-mirror/gcc/commit/96482ffe60d9bdec802fcad705c69641b2a3e040) and [P1064](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1064r0.html). It seems there's no obvious way to update default the GCC version in Azure Linux, so I decided to switch to C++17 for better compatibility. 
 - [x] Minor tweaks due to C++20 -> C++17.

## Tests
Local tests are all passed in gfx90a: [test_result_azurelinux.txt](https://github.com/user-attachments/files/16452048/test_result_azurelinux.txt)

### CODE REVIEW

**Review by jichangjichang — DISMISSED** [review]
lgtm

**Comment by KKyang** [comment]
Who is using Azure Linux?

**Comment by vin-huang** [comment]
> Who is using Azure Linux?

It's from [SWDEV-476705](https://ontrack-internal.amd.com/browse/SWDEV-476705)

**Review by jichangjichang — APPROVED** [review]
lgtm
btw, would this impact backward compatibility?

**Review by vin-huang — APPROVED** [review]
LGTM

**Comment by Serge45** [comment]
> lgtm btw, would this impact backward compatibility?

No, this change has no impact on binary compatibility.

**Pull request merged**
