### PR TITLE
Added F8HS TN Equality kernels for gfx942

### PR DESCRIPTION
**Pull request by pkamd**
Added 4 sizes for F8HS TN for aquavanjaram942 in Equality folder.

### CODE REVIEW

**Comment by aazz44ss** [comment]
Can you modify your commit name, it says you update F8HS NT

**Review by babakpst — APPROVED** [review]

**Comment by nakajee** [comment]
We do not actually have aquavanjaram942X folder in hipblaslt (that name exists only in rocblas).
You can simply use gfx942 here to follow the actual folder name in hipblaslt.

**Comment by nakajee** [comment]
> We do not actually have aquavanjaram942X folder in hipblaslt (that name exists only in rocblas). You can simply use gfx942 here to follow the actual folder name in hipblaslt.

Anyway, I updated the title.
Please make sure you use the updated title when merging the code.

**Comment by pkamd** [comment]
Closing this PR. New PR - https://github.com/ROCm/hipBLASLt/pull/1021 with better kernels has been raised. Also includes HHS tuning.

**Pull request closed without merging**
