### PR TITLE
gfx942 80cu BBS/HHS TN GridBased logic rebase

### PR DESCRIPTION
**Pull request by nakajee**

### CODE REVIEW

**Comment by nakajee** [comment]
- Rebased base GridBased logic with PR#795 (also ported same change to HHS)
- Re-merged initial tuning (PR#788) on top of the rebased base GridBased yaml (no new tuning in this PR)

**Comment by nakajee** [comment]
- 302 sizes and 5 kernels reduced by using rebased yaml (K=4096,8192 sizes)

**Review by aazz44ss — APPROVED** [review]

**Comment by nakajee** [comment]
gfx94x test failed due to link error.
This is not related to my change.

**Review by babakpst — APPROVED** [review]
Looks good. Thanks Koji.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
