### PR TITLE
Update NN/NT F8BS/F8HS Performance

### PR DESCRIPTION
**Pull request by ssuyuanchang**

### CODE REVIEW

**Review by hcman2 — APPROVED** [review]

**Review by KKyang — APPROVED** [review]

**Review by jichangjichang — CHANGES_REQUESTED** [review]
for Equality size, you set below restriction to get better perf
    AssertFree0ElementMultiple: 8
    AssertFree1ElementMultiple: 8
    AssertSummationElementMultiple: 32

**Comment by ssuyuanchang** [comment]
> for Equality size, you set below restriction to get better perf AssertFree0ElementMultiple: 8 AssertFree1ElementMultiple: 8 AssertSummationElementMultiple: 32

Done

**Review by jichangjichang — COMMENTED** [review]
lgtm

**Review by jichangjichang — APPROVED** [review]
lgtm

**Pull request merged**
