### PR TITLE
Feature/scale enhancements

### PR DESCRIPTION
**Pull request by brianchooou**
### [hipBLASLt] add Sample for ScaleA/B

Enhanced sample_hipblaslt_scale_a.cpp and sample_hipblaslt_scale_b.cpp with additional diagnostics and matrix size tests, updated CMakeLists.txt.

### CODE REVIEW

**Review by jichangjichang — COMMENTED** [review]
Are you sure that scale A/B can take effect?

**Comment by brianchooou** [comment]
> Are you sure that scale A/B can take effect?

Yes, based on the code implementation and the successful execution results, I am sure that the scale A/B operations are taking effect. Both simpleGemmScaleA and simpleGemmScaleB functions correctly set the scale pointers and successfully perform the matrix multiplication with scaling. The execution results showed in the picture prove that all heuristic solutions are successful, indicating that the operations, including scaling, are working as expected.

Picture1

**Comment by jichangjichang** [comment]
> > Are you sure that scale A/B can take effect?
> 
> Yes, based on the code implementation and the successful execution results, I am sure that the scale A/B operations are taking effect. Both simpleGemmScaleA and simpleGemmScaleB functions correctly set the scale pointers and successfully perform the matrix multiplication with scaling. The execution results showed in the picture prove that all heuristic solutions are successful, indicating that the operations, including scaling, are working as expected.
> 
> Picture1

return success doesn't mean scale A can take effect.

**Comment by vin-huang** [comment]
@jichangjichang 
do you mean there should be a validation section in this sample?

**Comment by jichangjichang** [comment]
> @jichangjichang do you mean there should be a validation section in this sample?

No, you just need to validate it atlocal side to make sure the sample is correct.

**Comment by brianchooou** [comment]
> > @jichangjichang do you mean there should be a validation section in this sample?
> 
> No, you just need to validate it atlocal side to make sure the sample is correct.

Got it, I will validate it and return the results for you to review soon.

**Comment by brianchooou** [comment]
Remove this PR and send a new PR soon

**Pull request closed without merging**
