### PR TITLE
Enable precision INT8 in hipBLASLt

### PR DESCRIPTION
**Pull request by AndySu12**
* Add gfx90a/941/942 GridBased INT8 yamls
* Enable hipBLASLt client
* Enable gtest
* Update documentation
* Fix ContractionSolution strideBias error when bias is not given

### CODE REVIEW

**Comment by AndySu12** [comment]
JIRA: [SWDEV-447304](https://ontrack-internal.amd.com/browse/SWDEV-447304)

**Review by hcman2 — APPROVED** [review]

**Review by KKyang — CHANGES_REQUESTED** [review]
Please use rebase instead of merge if possible

**Comment by KKyang** [comment]
Your commit message is "squash commits."

**Comment by AndySu12** [comment]
> Please use rebase instead of merge if possible

Done.

**Comment by AndySu12** [comment]
> Your commit message is "squash commits."

Done.

**Review by KKyang — APPROVED** [review]

**Pull request merged**
