### PR TITLE
Update gfx942 BBS Equality/GridBased yamls for 0811/0813/0815 sizes

### PR DESCRIPTION
**Pull request by AndySu12**

### CODE REVIEW

**Comment by jichangjichang** [comment]
Could you check the removed CustomKernel solution if any other solution refer to the same kernel? If No, we should remove the CustomKernel from tensilelite.

**Review by aazz44ss — APPROVED** [review]
LGTM

**Review by jichangjichang — APPROVED** [review]
lgtm

**Comment by AndySu12** [comment]
Local test passed.

[----------] Global test environment tear-down
[==========] 37294 tests from 13 test suites ran. (1838504 ms total)
[  PASSED  ] 37294 tests.
hipBLASLt version: 1000

**Pull request merged**
